openapi: 3.0.3
info:
  title: Bank Argent API documentation 1.0
  description: Documentation for using Bank Argent's API, for all action on transaction.
  version: 1.0.0
servers:
  - url: http://localhost:3001/api/v1
tags:
  - name: Transaction Module
    description: Everything about transaction
paths:
  /transaction/account:
    get:
      tags:
        - Transaction Module
      summary: Finds Account
      description: API for receive all account
      operationId: account
      parameters:
        - name: userID
          in: query
          description: User's ID is required to be fetched
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '400':
          description: Invalid user ID value
        '401':
          description: Unauthorized Error
        '500':
          description: Internal Server Error
      security:
        - APIKeyHeader : []
  /transaction/account/{accountId}:
    get:
      tags:
        - Transaction Module
      summary: Finds transaction
      description: API for receive all transaction
      operationId: transaction
      parameters:
        - name: accountId
          in: path
          description: Account's ID is required to be fetched
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionList'
        '400':
          description: Invalid account value
        '401':
          description: Unauthorized Error
        '500':
          description: Internal Server Error
      security:
        - APIKeyHeader : []
    put:
      tags:
        - Transaction Module
      summary: Change category or add note
      description: API for receive all transaction
      operationId: categoryAndNote
      parameters:
        - name: accountId
          in: path
          description: Account's ID is required to be fetched
          required: true
          schema:
            type: integer
            format: int64
        - name: transactionId
          in: query
          description: transaction's id is required to be fetched
          required: true
          schema:
            type: integer
            format: int64
        - name: category
          in: query
          description: Category if you wanna change 
          required: false
          schema:
            type: string
            default: food
            enum:
              - food
              - car
              - bill
              - other
        - name: note
          in: query
          description: Insert note if you wanna change 
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionList'
        '400':
          description: Invalid value
        '401':
          description: Unauthorized Error
        '500':
          description: Internal Server Error
      security:
        - APIKeyHeader : []
components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
        description:
          type: string
        amount:
          type: integer
          format: int64
        balance:
          type: integer
          format: int64
        type:
          type: string
        category:
          type: string
          default: food
          enum:
              - food
              - car
              - bill
              - other
        note:
          type: string
    TransactionList:
        required:
          - accountid
        type: object
        properties:
          transaction:
            type: array
            items:
              $ref: '#/components/schemas/Transaction'
    Account:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 439034093448
        name:
          type: string
          example: Argent Bank Checking
        balance:
          type: integer
          format: int64
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: Authorization